---
#Configuracion del Servidor
enableLoggingRequestDetails: false
server:
  error:
    include-message: always
    include-binding-errors: always
#Configuracion del log
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    dateformat: HH:mm:ss

#Suprimir el banner de Spring
spring:
  devtools:
    add-properties: false
  mvc:
    pathmatch:
      matching-strategy: "path-pattern-parser"
  main:
    web-application-type: reactive
    banner-mode: off
  #Configuracion de MySQL
  r2dbc:
    url: r2dbc:mysql://localhost:3306/partenon_db?useSSL=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
    pool:
      enabled: false
      max-size: 20
      validation-query: SELECT 1
      initial-size: 5
      max-idle-time: 30m
    data:
      r2dbc:
        repositories:
          enabled: true
  #Configuraciones de email
  mail:
    host: localhost
    port: 1025
    username: marcoslopezdev18@gmail.com
    password: scbqvqyyfvkxbqjr
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
jwt:
  secret: secret
  expired: 14400000
...


